<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Illuminate\Support\Facades\Http;

class ShowGameTest extends TestCase
{
    /** @test */
    public function the_game_page_shows_correct_game_info()
    {
        Http::fake([
            'https://api.igdb.com/v4/games'=>$this->fakeSingleGame()
        ]);

        $response = $this->get(route('games.show', 'cyberpunk-2077'));
        
        $response->assertSuccessful();
        $response->assertSee('Fake Cyberpunk 2077');
        $response->assertSee('PS4');
        $response->assertSee('Role-playing');
    }

    protected function fakeSingleGame()
    {
        return Http::response([
            0 => [
              'id' => 1877,
              'cover' => [
                'id' => 82217,
                'url' => '//images.igdb.com/igdb/image/upload/t_thumb/co1rft.jpg',
              ],
              'first_release_date' => 1607558400,
              'genres' => [
                0 => [
                  'id' => 12,
                  'name' => 'Role-playing (RPG)',
                ],
              ],
              'involved_companies' => [
                0 => [
                  'id' => 83211,
                  'company' => [
                    'id' => 6580,
                    'change_date_category' => 7,
                    'country' => 124,
                    'created_at' => 1442707200,
                    'logo' => 1787,
                    'name' => 'Digital Scapes Studios',
                    'slug' => 'digital-scapes-studios',
                    'start_date_category' => 7,
                    'updated_at' => 1566432000,
                    'url' => 'https://www.igdb.com/companies/digital-scapes-studios',
                    'websites' => [
                      0 => 443,
                    ],
                    'checksum' => '53505bfe-537c-53cb-e7bb-daf0883843af',
                  ],
                ],
                1 => [
                  'id' => 88888,
                  'company' => [
                    'id' => 19166,
                    'change_date_category' => 7,
                    'created_at' => 1555027200,
                    'name' => 'CD Projekt Red Wrocław',
                    'slug' => 'cd-projekt-red-wroclaw',
                    'start_date_category' => 7,
                    'updated_at' => 1577059200,
                    'url' => 'https://www.igdb.com/companies/cd-projekt-red-wroclaw',
                    'checksum' => 'bb10bed5-cab2-e677-4842-d7c17513fd37',
                  ],
                ],
                2 => [
                  'id' => 93176,
                  'company' => [
                    'id' => 774,
                    'change_date_category' => 7,
                    'country' => 616,
                    'created_at' => 1340150400,
                    'description' => '"QLOC specializes in providing the most needed services in the video game industry: porting, quality assurance, localisation and art outsourcing." 
           
          "Although we’re recognized worldwide as one of the best porting vendors, we’re more than just a bunch of cross-platform devs. Our team includes over 300 specialists 
          who are experienced in Quality Assurance, Localization and Art Design. We provide functional, compliance, localization and compatibility testing, 
          translate and localize games into 30 languages, and deliver 2D and 3D graphics, characters and concept art."',
                    'developed' => [
                      0 => 4797,
                      1 => 18150,
                      2 => 20850,
                      3 => 57660,
                      4 => 81085,
                    ],
                    'logo' => 1390,
                    'name' => 'QLOC',
                    'parent' => 8623,
                    'slug' => 'qloc',
                    'start_date' => 1262217600,
                    'start_date_category' => 2,
                    'updated_at' => 1588809600,
                    'url' => 'https://www.igdb.com/companies/qloc',
                    'websites' => [
                      0 => 1101,
                    ],
                    'checksum' => '74b18fec-c554-897d-5e7f-75db486ddee7',
                  ],
                ],
                3 => [
                  'id' => 99497,
                  'company' => [
                    'id' => 908,
                    'change_date_category' => 7,
                    'country' => 616,
                    'created_at' => 1357948800,
                    'description' => 'CD Projekt Red - a Polish video game developer, established in 2002 as a subsidiary of CD Projekt (the first company of this name, now CDP). The studio belonged to the holding CDP Investment, which was later merged with Optimus. The company\'s registered office was located in Warsaw. As part of the subsequent numerous transformations of the parent company, CD Projekt Red became a legal subsidiary of CD Projekt SA (until November 2012 CD Projekt Red SA).',
                    'developed' => [
                      0 => 80,
                      1 => 478,
                      2 => 1877,
                      3 => 1942,
                      4 => 8765,
                      5 => 9689,
                      6 => 12503,
                      7 => 13166,
                      8 => 19474,
                      9 => 20275,
                      10 => 20740,
                      11 => 22439,
                      12 => 27832,
                      13 => 80342,
                      14 => 107300,
                      15 => 115776,
                      16 => 119402,
                    ],
                    'logo' => 3080,
                    'name' => 'CD Projekt RED',
                    'parent' => 4291,
                    'published' => [
                      0 => 80,
                      1 => 478,
                      2 => 1877,
                      3 => 8285,
                      4 => 9689,
                      5 => 12503,
                      6 => 19474,
                      7 => 27832,
                      8 => 107300,
                      9 => 115776,
                      10 => 119402,
                    ],
                    'slug' => 'cd-projekt-red',
                    'start_date' => 1012521600,
                    'start_date_category' => 1,
                    'updated_at' => 1580169600,
                    'url' => 'https://www.igdb.com/companies/cd-projekt-red',
                    'websites' => [
                      0 => 849,
                    ],
                    'checksum' => '3f8dd510-bc5d-1005-01e4-ae0af15c3415',
                  ],
                ],
              ],
              'name' => 'Fake Cyberpunk 2077',
              'platforms' => [
                0 => [
                  'id' => 6,
                  'abbreviation' => 'PC',
                ],
                1 => [
                  'id' => 48,
                  'abbreviation' => 'PS4',
                ],
                2 => [
                  'id' => 49,
                  'abbreviation' => 'XONE',
                ],
                3 => [
                  'id' => 167,
                  'abbreviation' => 'PS5',
                ],
                4 => [
                  'id' => 169,
                  'abbreviation' => 'Series X',
                ],
                5 => [
                  'id' => 170,
                  'abbreviation' => 'Stadia',
                ],
              ],
              'screenshots' => [
                0 => [
                  'id' => 214060,
                  'url' => '//images.igdb.com/igdb/image/upload/t_thumb/quphnww1axg2mmsvxfux.jpg',
                ],
                1 => [
                  'id' => 214061,
                  'url' => '//images.igdb.com/igdb/image/upload/t_thumb/jmi4y3q12o4uitdcaf7i.jpg',
                ],
                2 => [
                  'id' => 214062,
                  'url' => '//images.igdb.com/igdb/image/upload/t_thumb/c6ruovzsugjlnlcmm8b0.jpg',
                ],
                3 => [
                  'id' => 214063,
                  'url' => '//images.igdb.com/igdb/image/upload/t_thumb/ydyq0pixly7vt29fnzci.jpg',
                ],
                4 => [
                  'id' => 214064,
                  'url' => '//images.igdb.com/igdb/image/upload/t_thumb/lelfskpwy4slftl3qdeb.jpg',
                ],
                5 => [
                  'id' => 214066,
                  'url' => '//images.igdb.com/igdb/image/upload/t_thumb/c7usjg7gpo8rs0bfjkph.jpg',
                ],
                6 => [
                  'id' => 214067,
                  'url' => '//images.igdb.com/igdb/image/upload/t_thumb/ybliaszwqkwui7djaou4.jpg',
                ],
                7 => [
                  'id' => 214068,
                  'url' => '//images.igdb.com/igdb/image/upload/t_thumb/ts8wtae3t6aghttvtt2s.jpg',
                ],
                8 => [
                  'id' => 214069,
                  'url' => '//images.igdb.com/igdb/image/upload/t_thumb/vnv5cd9kvonsjvazpotx.jpg',
                ],
                9 => [
                  'id' => 214070,
                  'url' => '//images.igdb.com/igdb/image/upload/t_thumb/w4plqrhe04byymfksmux.jpg',
                ],
                10 => [
                  'id' => 214071,
                  'url' => '//images.igdb.com/igdb/image/upload/t_thumb/ubbe5gewccx5ig3xy30t.jpg',
                ],
              ],
              'similar_games' => [
                0 => [
                  'id' => 9243,
                  'cover' => [
                    'id' => 13044,
                    'url' => '//images.igdb.com/igdb/image/upload/t_thumb/ttaatqkearykpgkmz0ad.jpg',
                  ],
                  'name' => 'Life is Feudal: Your Own',
                  'platforms' => [
                    0 => [
                      'id' => 6,
                      'abbreviation' => 'PC',
                      'alternative_name' => 'mswin',
                      'category' => 4,
                      'created_at' => 1297555200,
                      'name' => 'PC (Microsoft Windows)',
                      'platform_logo' => 203,
                      'slug' => 'win',
                      'updated_at' => 1470009600,
                      'url' => 'https://www.igdb.com/platforms/win',
                      'versions' => [
                        0 => 1,
                        1 => 13,
                        2 => 14,
                        3 => 15,
                        4 => 124,
                      ],
                      'websites' => [
                        0 => 2,
                      ],
                      'checksum' => '5aae54d0-390e-a4ec-a9ee-4ad4cc346992',
                    ],
                  ],
                  'rating' => 66.3186733958183,
                  'slug' => 'life-is-feudal-your-own',
                ],
                1 => [
                  'id' => 10776,
                  'cover' => [
                    'id' => 85495,
                    'url' => '//images.igdb.com/igdb/image/upload/t_thumb/co1tyv.jpg',
                  ],
                  'name' => 'Rising World',
                  'platforms' => [
                    0 => [
                      'id' => 3,
                      'abbreviation' => 'Linux',
                      'alternative_name' => 'GNU/Linux',
                      'category' => 4,
                      'created_at' => 1297555200,
                      'name' => 'Linux',
                      'platform_logo' => 380,
                      'platform_family' => 4,
                      'slug' => 'linux',
                      'summary' => 'Linux is a free and open-source (FOSS/FLOSS) Operating System. In a more precise and complex definition, Linux is an open-source OS kernel on which a large variety of Operating Systems (known as Linux distributions) are built.',
                      'updated_at' => 1392940800,
                      'url' => 'https://www.igdb.com/platforms/linux',
                      'versions' => [
                        0 => 44,
                      ],
                      'websites' => [
                        0 => 1,
                      ],
                      'checksum' => 'b810fb9c-65f7-b297-3658-da9c4d52bf11',
                    ],
                    1 => [
                      'id' => 6,
                      'abbreviation' => 'PC',
                      'alternative_name' => 'mswin',
                      'category' => 4,
                      'created_at' => 1297555200,
                      'name' => 'PC (Microsoft Windows)',
                      'platform_logo' => 203,
                      'slug' => 'win',
                      'updated_at' => 1470009600,
                      'url' => 'https://www.igdb.com/platforms/win',
                      'versions' => [
                        0 => 1,
                        1 => 13,
                        2 => 14,
                        3 => 15,
                        4 => 124,
                      ],
                      'websites' => [
                        0 => 2,
                      ],
                      'checksum' => '5aae54d0-390e-a4ec-a9ee-4ad4cc346992',
                    ],
                    2 => [
                      'id' => 14,
                      'abbreviation' => 'Mac',
                      'alternative_name' => 'Mac OS',
                      'category' => 4,
                      'created_at' => 1297641600,
                      'name' => 'Mac',
                      'platform_logo' => 100,
                      'slug' => 'mac',
                      'updated_at' => 1394236800,
                      'url' => 'https://www.igdb.com/platforms/mac',
                      'versions' => [
                        0 => 45,
                        1 => 141,
                        2 => 142,
                        3 => 143,
                        4 => 144,
                        5 => 145,
                        6 => 146,
                        7 => 147,
                        8 => 148,
                        9 => 149,
                        10 => 150,
                        11 => 151,
                      ],
                      'websites' => [
                        0 => 5,
                      ],
                      'checksum' => '19c9dcae-80a2-e137-50ff-11b823738827',
                    ],
                  ],
                  'rating' => 80.0,
                  'slug' => 'rising-world',
                ],
                2 => [
                  'id' => 18290,
                  'cover' => [
                    'id' => 82265,
                    'url' => '//images.igdb.com/igdb/image/upload/t_thumb/co1rh5.jpg',
                  ],
                  'name' => 'Grav',
                  'platforms' => [
                    0 => [
                      'id' => 6,
                      'abbreviation' => 'PC',
                      'alternative_name' => 'mswin',
                      'category' => 4,
                      'created_at' => 1297555200,
                      'name' => 'PC (Microsoft Windows)',
                      'platform_logo' => 203,
                      'slug' => 'win',
                      'updated_at' => 1470009600,
                      'url' => 'https://www.igdb.com/platforms/win',
                      'versions' => [
                        0 => 1,
                        1 => 13,
                        2 => 14,
                        3 => 15,
                        4 => 124,
                      ],
                      'websites' => [
                        0 => 2,
                      ],
                      'checksum' => '5aae54d0-390e-a4ec-a9ee-4ad4cc346992',
                    ],
                  ],
                  'rating' => 55.0452850274847,
                  'slug' => 'grav',
                ],
                3 => [
                  'id' => 19249,
                  'cover' => [
                    'id' => 69438,
                    'url' => '//images.igdb.com/igdb/image/upload/t_thumb/co1hku.jpg',
                  ],
                  'name' => 'Empyrion - Galactic Survival',
                  'platforms' => [
                    0 => [
                      'id' => 6,
                      'abbreviation' => 'PC',
                      'alternative_name' => 'mswin',
                      'category' => 4,
                      'created_at' => 1297555200,
                      'name' => 'PC (Microsoft Windows)',
                      'platform_logo' => 203,
                      'slug' => 'win',
                      'updated_at' => 1470009600,
                      'url' => 'https://www.igdb.com/platforms/win',
                      'versions' => [
                        0 => 1,
                        1 => 13,
                        2 => 14,
                        3 => 15,
                        4 => 124,
                      ],
                      'websites' => [
                        0 => 2,
                      ],
                      'checksum' => '5aae54d0-390e-a4ec-a9ee-4ad4cc346992',
                    ],
                  ],
                  'rating' => 68.9295356228651,
                  'slug' => 'empyrion-galactic-survival',
                ],
                4 => [
                  'id' => 25300,
                  'cover' => [
                    'id' => 67720,
                    'url' => '//images.igdb.com/igdb/image/upload/t_thumb/vz1tifvufvwi6rd4zmz7.jpg',
                  ],
                  'name' => 'Sky Break',
                  'platforms' => [
                    0 => [
                      'id' => 3,
                      'abbreviation' => 'Linux',
                      'alternative_name' => 'GNU/Linux',
                      'category' => 4,
                      'created_at' => 1297555200,
                      'name' => 'Linux',
                      'platform_logo' => 380,
                      'platform_family' => 4,
                      'slug' => 'linux',
                      'summary' => 'Linux is a free and open-source (FOSS/FLOSS) Operating System. In a more precise and complex definition, Linux is an open-source OS kernel on which a large variety of Operating Systems (known as Linux distributions) are built.',
                      'updated_at' => 1392940800,
                      'url' => 'https://www.igdb.com/platforms/linux',
                      'versions' => [
                        0 => 44,
                      ],
                      'websites' => [
                        0 => 1,
                      ],
                      'checksum' => 'b810fb9c-65f7-b297-3658-da9c4d52bf11',
                    ],
                    1 => [
                      'id' => 6,
                      'abbreviation' => 'PC',
                      'alternative_name' => 'mswin',
                      'category' => 4,
                      'created_at' => 1297555200,
                      'name' => 'PC (Microsoft Windows)',
                      'platform_logo' => 203,
                      'slug' => 'win',
                      'updated_at' => 1470009600,
                      'url' => 'https://www.igdb.com/platforms/win',
                      'versions' => [
                        0 => 1,
                        1 => 13,
                        2 => 14,
                        3 => 15,
                        4 => 124,
                      ],
                      'websites' => [
                        0 => 2,
                      ],
                      'checksum' => '5aae54d0-390e-a4ec-a9ee-4ad4cc346992',
                    ],
                    2 => [
                      'id' => 14,
                      'abbreviation' => 'Mac',
                      'alternative_name' => 'Mac OS',
                      'category' => 4,
                      'created_at' => 1297641600,
                      'name' => 'Mac',
                      'platform_logo' => 100,
                      'slug' => 'mac',
                      'updated_at' => 1394236800,
                      'url' => 'https://www.igdb.com/platforms/mac',
                      'versions' => [
                        0 => 45,
                        1 => 141,
                        2 => 142,
                        3 => 143,
                        4 => 144,
                        5 => 145,
                        6 => 146,
                        7 => 147,
                        8 => 148,
                        9 => 149,
                        10 => 150,
                        11 => 151,
                      ],
                      'websites' => [
                        0 => 5,
                      ],
                      'checksum' => '19c9dcae-80a2-e137-50ff-11b823738827',
                    ],
                  ],
                  'rating' => 52.0351611847471,
                  'slug' => 'sky-break',
                ],
                5 => [
                  'id' => 26574,
                  'cover' => [
                    'id' => 82161,
                    'url' => '//images.igdb.com/igdb/image/upload/t_thumb/co1re9.jpg',
                  ],
                  'name' => 'Force of Nature',
                  'platforms' => [
                    0 => [
                      'id' => 6,
                      'abbreviation' => 'PC',
                      'alternative_name' => 'mswin',
                      'category' => 4,
                      'created_at' => 1297555200,
                      'name' => 'PC (Microsoft Windows)',
                      'platform_logo' => 203,
                      'slug' => 'win',
                      'updated_at' => 1470009600,
                      'url' => 'https://www.igdb.com/platforms/win',
                      'versions' => [
                        0 => 1,
                        1 => 13,
                        2 => 14,
                        3 => 15,
                        4 => 124,
                      ],
                      'websites' => [
                        0 => 2,
                      ],
                      'checksum' => '5aae54d0-390e-a4ec-a9ee-4ad4cc346992',
                    ],
                  ],
                  'rating' => 60.0,
                  'slug' => 'force-of-nature',
                ],
                6 => [
                  'id' => 54842,
                  'cover' => [
                    'id' => 82670,
                    'url' => '//images.igdb.com/igdb/image/upload/t_thumb/co1rse.jpg',
                  ],
                  'name' => 'Biomutant',
                  'platforms' => [
                    0 => [
                      'id' => 6,
                      'abbreviation' => 'PC',
                      'alternative_name' => 'mswin',
                      'category' => 4,
                      'created_at' => 1297555200,
                      'name' => 'PC (Microsoft Windows)',
                      'platform_logo' => 203,
                      'slug' => 'win',
                      'updated_at' => 1470009600,
                      'url' => 'https://www.igdb.com/platforms/win',
                      'versions' => [
                        0 => 1,
                        1 => 13,
                        2 => 14,
                        3 => 15,
                        4 => 124,
                      ],
                      'websites' => [
                        0 => 2,
                      ],
                      'checksum' => '5aae54d0-390e-a4ec-a9ee-4ad4cc346992',
                    ],
                    1 => [
                      'id' => 48,
                      'abbreviation' => 'PS4',
                      'alternative_name' => 'PS4',
                      'category' => 1,
                      'created_at' => 1326499200,
                      'generation' => 8,
                      'name' => 'PlayStation 4',
                      'platform_logo' => 231,
                      'platform_family' => 1,
                      'slug' => 'ps4--1',
                      'summary' => 'The PlayStation 4 system opens the door to an incredible journey through immersive new gaming worlds and a deeply connected gaming community. PS4 puts gamers first with an astounding launch line-up and over 180 games in development. Play amazing top-tier blockbusters and innovative indie hits on PS4. Developer inspired, gamer focused.',
                      'updated_at' => 1433116800,
                      'url' => 'https://www.igdb.com/platforms/ps4--1',
                      'versions' => [
                        0 => 17,
                        1 => 178,
                        2 => 179,
                      ],
                      'websites' => [
                        0 => 11,
                      ],
                      'checksum' => '1dfa9b83-5f1d-56ce-01a1-06fcdfbb5bc0',
                    ],
                    2 => [
                      'id' => 49,
                      'abbreviation' => 'XONE',
                      'alternative_name' => 'Xbone',
                      'category' => 1,
                      'created_at' => 1326499200,
                      'generation' => 8,
                      'name' => 'Xbox One',
                      'platform_logo' => 329,
                      'platform_family' => 2,
                      'slug' => 'xboxone',
                      'summary' => 'Welcome to a new generation of games and entertainment. Where games push the boundaries of realism. And television obeys your every command. Where listening to music while playing a game is a snap. And you can jump from TV to movies to music to a game in an instant. Where your experience is custom tailored to you. And the entertainment you love is all in one place. Welcome to the all-in-one, Xbox One',
                      'updated_at' => 1429920000,
                      'url' => 'https://www.igdb.com/platforms/xboxone',
                      'versions' => [
                        0 => 78,
                        1 => 180,
                        2 => 185,
                        3 => 188,
                      ],
                      'websites' => [
                        0 => 12,
                      ],
                      'checksum' => 'd2560055-3c6f-d1f6-c5a4-483d9a15498a',
                    ],
                  ],
                  'slug' => 'biomutant',
                ],
                7 => [
                  'id' => 55038,
                  'cover' => [
                    'id' => 82160,
                    'url' => '//images.igdb.com/igdb/image/upload/t_thumb/co1re8.jpg',
                  ],
                  'name' => 'Immortal: Unchained',
                  'platforms' => [
                    0 => [
                      'id' => 6,
                      'abbreviation' => 'PC',
                      'alternative_name' => 'mswin',
                      'category' => 4,
                      'created_at' => 1297555200,
                      'name' => 'PC (Microsoft Windows)',
                      'platform_logo' => 203,
                      'slug' => 'win',
                      'updated_at' => 1470009600,
                      'url' => 'https://www.igdb.com/platforms/win',
                      'versions' => [
                        0 => 1,
                        1 => 13,
                        2 => 14,
                        3 => 15,
                        4 => 124,
                      ],
                      'websites' => [
                        0 => 2,
                      ],
                      'checksum' => '5aae54d0-390e-a4ec-a9ee-4ad4cc346992',
                    ],
                    1 => [
                      'id' => 48,
                      'abbreviation' => 'PS4',
                      'alternative_name' => 'PS4',
                      'category' => 1,
                      'created_at' => 1326499200,
                      'generation' => 8,
                      'name' => 'PlayStation 4',
                      'platform_logo' => 231,
                      'platform_family' => 1,
                      'slug' => 'ps4--1',
                      'summary' => 'The PlayStation 4 system opens the door to an incredible journey through immersive new gaming worlds and a deeply connected gaming community. PS4 puts gamers first with an astounding launch line-up and over 180 games in development. Play amazing top-tier blockbusters and innovative indie hits on PS4. Developer inspired, gamer focused.',
                      'updated_at' => 1433116800,
                      'url' => 'https://www.igdb.com/platforms/ps4--1',
                      'versions' => [
                        0 => 17,
                        1 => 178,
                        2 => 179,
                      ],
                      'websites' => [
                        0 => 11,
                      ],
                      'checksum' => '1dfa9b83-5f1d-56ce-01a1-06fcdfbb5bc0',
                    ],
                    2 => [
                      'id' => 49,
                      'abbreviation' => 'XONE',
                      'alternative_name' => 'Xbone',
                      'category' => 1,
                      'created_at' => 1326499200,
                      'generation' => 8,
                      'name' => 'Xbox One',
                      'platform_logo' => 329,
                      'platform_family' => 2,
                      'slug' => 'xboxone',
                      'summary' => 'Welcome to a new generation of games and entertainment. Where games push the boundaries of realism. And television obeys your every command. Where listening to music while playing a game is a snap. And you can jump from TV to movies to music to a game in an instant. Where your experience is custom tailored to you. And the entertainment you love is all in one place. Welcome to the all-in-one, Xbox One',
                      'updated_at' => 1429920000,
                      'url' => 'https://www.igdb.com/platforms/xboxone',
                      'versions' => [
                        0 => 78,
                        1 => 180,
                        2 => 185,
                        3 => 188,
                      ],
                      'websites' => [
                        0 => 12,
                      ],
                      'checksum' => 'd2560055-3c6f-d1f6-c5a4-483d9a15498a',
                    ],
                  ],
                  'rating' => 59.5854922279793,
                  'slug' => 'immortal-unchained',
                ],
                8 => [
                  'id' => 113114,
                  'cover' => [
                    'id' => 111992,
                    'url' => '//images.igdb.com/igdb/image/upload/t_thumb/co2eew.jpg',
                  ],
                  'name' => 'The Outer Worlds',
                  'platforms' => [
                    0 => [
                      'id' => 6,
                      'abbreviation' => 'PC',
                      'alternative_name' => 'mswin',
                      'category' => 4,
                      'created_at' => 1297555200,
                      'name' => 'PC (Microsoft Windows)',
                      'platform_logo' => 203,
                      'slug' => 'win',
                      'updated_at' => 1470009600,
                      'url' => 'https://www.igdb.com/platforms/win',
                      'versions' => [
                        0 => 1,
                        1 => 13,
                        2 => 14,
                        3 => 15,
                        4 => 124,
                      ],
                      'websites' => [
                        0 => 2,
                      ],
                      'checksum' => '5aae54d0-390e-a4ec-a9ee-4ad4cc346992',
                    ],
                    1 => [
                      'id' => 48,
                      'abbreviation' => 'PS4',
                      'alternative_name' => 'PS4',
                      'category' => 1,
                      'created_at' => 1326499200,
                      'generation' => 8,
                      'name' => 'PlayStation 4',
                      'platform_logo' => 231,
                      'platform_family' => 1,
                      'slug' => 'ps4--1',
                      'summary' => 'The PlayStation 4 system opens the door to an incredible journey through immersive new gaming worlds and a deeply connected gaming community. PS4 puts gamers first with an astounding launch line-up and over 180 games in development. Play amazing top-tier blockbusters and innovative indie hits on PS4. Developer inspired, gamer focused.',
                      'updated_at' => 1433116800,
                      'url' => 'https://www.igdb.com/platforms/ps4--1',
                      'versions' => [
                        0 => 17,
                        1 => 178,
                        2 => 179,
                      ],
                      'websites' => [
                        0 => 11,
                      ],
                      'checksum' => '1dfa9b83-5f1d-56ce-01a1-06fcdfbb5bc0',
                    ],
                    2 => [
                      'id' => 49,
                      'abbreviation' => 'XONE',
                      'alternative_name' => 'Xbone',
                      'category' => 1,
                      'created_at' => 1326499200,
                      'generation' => 8,
                      'name' => 'Xbox One',
                      'platform_logo' => 329,
                      'platform_family' => 2,
                      'slug' => 'xboxone',
                      'summary' => 'Welcome to a new generation of games and entertainment. Where games push the boundaries of realism. And television obeys your every command. Where listening to music while playing a game is a snap. And you can jump from TV to movies to music to a game in an instant. Where your experience is custom tailored to you. And the entertainment you love is all in one place. Welcome to the all-in-one, Xbox One',
                      'updated_at' => 1429920000,
                      'url' => 'https://www.igdb.com/platforms/xboxone',
                      'versions' => [
                        0 => 78,
                        1 => 180,
                        2 => 185,
                        3 => 188,
                      ],
                      'websites' => [
                        0 => 12,
                      ],
                      'checksum' => 'd2560055-3c6f-d1f6-c5a4-483d9a15498a',
                    ],
                    3 => [
                      'id' => 130,
                      'abbreviation' => 'Switch',
                      'alternative_name' => 'NX',
                      'category' => 1,
                      'created_at' => 1465948800,
                      'generation' => 8,
                      'name' => 'Nintendo Switch',
                      'platform_logo' => 534,
                      'platform_family' => 5,
                      'slug' => 'switch',
                      'updated_at' => 1550534400,
                      'url' => 'https://www.igdb.com/platforms/switch',
                      'versions' => [
                        0 => 173,
                        1 => 282,
                      ],
                      'websites' => [
                        0 => 16,
                      ],
                      'checksum' => 'd28b6757-c24a-73c6-50e7-f8e6487c78af',
                    ],
                    4 => [
                      'id' => 169,
                      'abbreviation' => 'Series X',
                      'category' => 1,
                      'created_at' => 1565222400,
                      'generation' => 9,
                      'name' => 'Xbox Series',
                      'platform_logo' => 561,
                      'platform_family' => 2,
                      'slug' => 'series-x',
                      'updated_at' => 1603238400,
                      'url' => 'https://www.igdb.com/platforms/series-x',
                      'versions' => [
                        0 => 284,
                      ],
                      'websites' => [
                        0 => 36,
                        1 => 105,
                        2 => 238,
                      ],
                      'checksum' => '98496e66-2edc-77a1-7d7c-6f518c65f469',
                    ],
                  ],
                  'rating' => 84.65689790999059,
                  'slug' => 'the-outer-worlds',
                ],
              ],
              'slug' => 'cyberpunk-2077',
              'summary' => 'Cyberpunk 2077 is a role-playing video game developed and published by CD Projekt. Adapted from the Cyberpunk franchise, the game is an open world, non-linear RPG with an FPS style in which players are able to heavily customize their character to suit their play style. Gun play, exploration, player choice and activities such as hacking are to feature heavily throughout the game with missions, quests and objectives being completed in a variety of different ways. The world will have dynamic weather and a day/night cycle to make it truly immersive.',
              'videos' => [
                0 => [
                  'id' => 2743,
                  'game' => 1877,
                  'name' => 'Teaser',
                  'video_id' => '6eS7CX5zkj0',
                  'checksum' => '5182c458-d633-f361-57b1-b6fdc46eed5b',
                ],
                1 => [
                  'id' => 27840,
                  'game' => 1877,
                  'name' => 'Trailer',
                  'video_id' => 'qIcTM8WXFjk',
                  'checksum' => 'd5ac91ec-db19-9686-44c7-6e15218b98a3',
                ],
                2 => [
                  'id' => 36456,
                  'game' => 1877,
                  'name' => 'Gameplay Trailer',
                  'video_id' => 'FknHjl7eQ6o',
                  'checksum' => '2a7a8b10-f674-3c59-0ae5-f6ef7305dd6e',
                ],
                3 => [
                  'id' => 36457,
                  'game' => 1877,
                  'name' => 'Trailer',
                  'video_id' => '9cOHWnklYGw',
                  'checksum' => 'c9d1e5d1-99d2-1709-924b-26681e0fd066',
                ],
                4 => [
                  'id' => 36458,
                  'game' => 1877,
                  'name' => 'Gameplay Video',
                  'video_id' => 'vjF9GgrY9c0',
                  'checksum' => '745e4acb-6365-695f-339c-8067a7692d7e',
                ],
              ],
              'websites' => [
                0 => [
                  'id' => 360,
                  'category' => 1,
                  'game' => 1877,
                  'trusted' => false,
                  'url' => 'http://cyberpunk.net/',
                  'checksum' => '441cb8fe-2da4-ac3d-463e-2ec6f759662e',
                ],
                1 => [
                  'id' => 57810,
                  'category' => 3,
                  'game' => 1877,
                  'trusted' => true,
                  'url' => 'https://en.wikipedia.org/wiki/Cyberpunk_2077',
                  'checksum' => '05f99da1-b626-4b5f-9b0b-d0b9142a970c',
                ],
                2 => [
                  'id' => 57811,
                  'category' => 4,
                  'game' => 1877,
                  'trusted' => true,
                  'url' => 'https://www.facebook.com/CyberpunkGame',
                  'checksum' => '452baed7-fdd0-63bc-b26a-4b5db82f562b',
                ],
                3 => [
                  'id' => 57812,
                  'category' => 5,
                  'game' => 1877,
                  'trusted' => true,
                  'url' => 'https://twitter.com/CyberpunkGame',
                  'checksum' => '056ae5a7-ba33-0481-bfee-00b736e08ede',
                ],
                4 => [
                  'id' => 57813,
                  'category' => 9,
                  'game' => 1877,
                  'trusted' => true,
                  'url' => 'https://www.youtube.com/user/CyberPunkGame',
                  'checksum' => 'aceea119-08c0-7595-fd3e-a887fceda1f4',
                ],
                5 => [
                  'id' => 108258,
                  'category' => 13,
                  'game' => 1877,
                  'trusted' => true,
                  'url' => 'https://store.steampowered.com/app/1091500/Cyberpunk_2077/',
                  'checksum' => '2db788d9-aecc-d727-9c62-7b7bf209f339',
                ],
                6 => [
                  'id' => 117115,
                  'category' => 8,
                  'game' => 1877,
                  'trusted' => true,
                  'url' => 'https://www.instagram.com/cyberpunkgame',
                  'checksum' => '4f5fc915-baa1-a4a6-153b-fdad509a141d',
                ],
                7 => [
                  'id' => 120137,
                  'category' => 14,
                  'game' => 1877,
                  'trusted' => true,
                  'url' => 'https://www.reddit.com/r/cyberpunkgame',
                  'checksum' => 'c648cb3c-cbcf-3fef-7baf-39820d19ceef',
                ],
                8 => [
                  'id' => 120138,
                  'category' => 16,
                  'game' => 1877,
                  'trusted' => true,
                  'url' => 'https://www.epicgames.com/store/product/cyberpunk-2077/home',
                  'checksum' => '11a8d2ea-921e-c1fd-b30e-8775dcfe4aaf',
                ],
                9 => [
                  'id' => 120139,
                  'category' => 17,
                  'game' => 1877,
                  'trusted' => true,
                  'url' => 'https://www.gog.com/game/cyberpunk_2077',
                  'checksum' => 'a8bfc28e-e699-b377-e612-c28df8aa0bbd',
                ],
                10 => [
                  'id' => 139070,
                  'category' => 18,
                  'game' => 1877,
                  'trusted' => true,
                  'url' => 'https://discordapp.com/invite/cyberpunkgame',
                  'checksum' => '5f8e71cc-a3a2-10a3-43ff-b5e0c1f8f24f',
                ],
              ],
            ],
          ], 200); 
    }
}
